### PR TITLE
Login/registration

### PR DESCRIPTION
**Pull request by Briiick**
- Login and registration styling done.
- Will be doing endpoints next.
- need to figure out vertical alignment.

### CODE REVIEW

**Comment by bathientran** [comment]
LGTM - I'll let @alexander-wu-aw review and then merge, he seems to know a bit more about the frontend and can direct it. If you want me to resolve conflicts lmk.

**Comment by alexander-wu-aw** [comment]
So Login and Registration on small devices (when width is small) looks weird.

**Comment by alexander-wu-aw** [comment]
And yea maybe try to figure out vertical alignment? Try exploring flexbox

**Comment by alexander-wu-aw** [comment]
Other than that all good

**Pull request merged**
